apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-vault-token
  namespace: default
data:
  token: 'aHZzLkNBRVNJUDZQbEJaSDJYTm04ejhSbWgzREpIUEJxb3VNNmxfQmJfLXZIZG9Kei1lZ0doNEtIR2gyY3k1allUWnlWVzFKYUdGM1IyZHRTRE0xUzJZelRWTmpTRFEK'
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: default
spec:
  vault:
    server: http://192.168.56.108:8200
    path: pki_int/sign/edgesite-dot-com
    auth:
      tokenSecretRef:
          name: my-vault-token
          key: token
---
 apiVersion: cert-manager.io/v1
 kind: Certificate
 metadata:
   name: cert-from-vault
   namespace: default
 spec:
   commonName: alpha.edgesite.com
   secretName: vault-cert-secret-tls
   issuerRef:
     name: vault-issuer
   dnsNames:
   - alpha.edgesite.com
