apiVersion: v1
kind: PersistentVolume
metadata:
  name: ks-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/sysadmin/WORKING"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ks-pvc
  namespace: killswitch-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
