apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: killswitch-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: killswitch
  namespace: killswitch-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-cert-control
rules:
  - apiGroups:
      - ""
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - get
      - list
      - delete
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-agent-rb
  namespace: default 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-cert-control
subjects:
- kind: ServiceAccount
  name: killswitch
  namespace: killswitch-ns
