apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-vault-token
  namespace: default
data:
  token: 'aHZzLkNBRVNJSFJQNmZZaWFGblJnd2JMMThSZlJKNmRIYW1JSDBJRTRpLS1SMXhvdlN1bUdoNEtIR2gyY3k1cVFsZDFOSGRETjI5UFlrUklNV0pYZFRRellYazRlRk0K'
---
