apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: default
spec:
  vault:
    server: http://192.168.56.108:8200
    path: pki_int/sign/edgesite-dot-com
    auth:
      tokenSecretRef:
          name: my-vault-token
          key: token
